require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AsociateDocumentTypesController do

  # This should return the minimal set of attributes required to create a valid
  # AssociatedDocumentType. As you add validations to AssociatedDocumentType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all associated_document_types as @associated_document_types" do
      asociate_document_type = AssociatedDocumentType.create! valid_attributes
      get :index
      assigns(:asociate_document_types).should eq([asociate_document_type])
    end
  end

  describe "GET show" do
    it "assigns the requested asociate_document_type as @asociate_document_type" do
      asociate_document_type = AssociatedDocumentType.create! valid_attributes
      get :show, :id => asociate_document_type.id.to_s
      assigns(:asociate_document_type).should eq(asociate_document_type)
    end
  end

  describe "GET new" do
    it "assigns a new asociate_document_type as @asociate_document_type" do
      get :new
      assigns(:asociate_document_type).should be_a_new(AssociatedDocumentType)
    end
  end

  describe "GET edit" do
    it "assigns the requested asociate_document_type as @asociate_document_type" do
      asociate_document_type = AssociatedDocumentType.create! valid_attributes
      get :edit, :id => asociate_document_type.id.to_s
      assigns(:asociate_document_type).should eq(asociate_document_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssociatedDocumentType" do
        expect {
          post :create, :asociate_document_type => valid_attributes
        }.to change(AssociatedDocumentType, :count).by(1)
      end

      it "assigns a newly created asociate_document_type as @asociate_document_type" do
        post :create, :asociate_document_type => valid_attributes
        assigns(:asociate_document_type).should be_a(AssociatedDocumentType)
        assigns(:asociate_document_type).should be_persisted
      end

      it "redirects to the created asociate_document_type" do
        post :create, :asociate_document_type => valid_attributes
        response.should redirect_to(AssociatedDocumentType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved asociate_document_type as @asociate_document_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssociatedDocumentType.any_instance.stub(:save).and_return(false)
        post :create, :asociate_document_type => {}
        assigns(:asociate_document_type).should be_a_new(AssociatedDocumentType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssociatedDocumentType.any_instance.stub(:save).and_return(false)
        post :create, :asociate_document_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested asociate_document_type" do
        asociate_document_type = AssociatedDocumentType.create! valid_attributes
        # Assuming there are no other associated_document_types in the database, this
        # specifies that the AssociatedDocumentType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssociatedDocumentType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => asociate_document_type.id, :asociate_document_type => {'these' => 'params'}
      end

      it "assigns the requested asociate_document_type as @asociate_document_type" do
        asociate_document_type = AssociatedDocumentType.create! valid_attributes
        put :update, :id => asociate_document_type.id, :asociate_document_type => valid_attributes
        assigns(:asociate_document_type).should eq(asociate_document_type)
      end

      it "redirects to the asociate_document_type" do
        asociate_document_type = AssociatedDocumentType.create! valid_attributes
        put :update, :id => asociate_document_type.id, :asociate_document_type => valid_attributes
        response.should redirect_to(asociate_document_type)
      end
    end

    describe "with invalid params" do
      it "assigns the asociate_document_type as @asociate_document_type" do
        asociate_document_type = AssociatedDocumentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssociatedDocumentType.any_instance.stub(:save).and_return(false)
        put :update, :id => asociate_document_type.id.to_s, :asociate_document_type => {}
        assigns(:asociate_document_type).should eq(asociate_document_type)
      end

      it "re-renders the 'edit' template" do
        asociate_document_type = AssociatedDocumentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssociatedDocumentType.any_instance.stub(:save).and_return(false)
        put :update, :id => asociate_document_type.id.to_s, :asociate_document_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested asociate_document_type" do
      asociate_document_type = AssociatedDocumentType.create! valid_attributes
      expect {
        delete :destroy, :id => asociate_document_type.id.to_s
      }.to change(AssociatedDocumentType, :count).by(-1)
    end

    it "redirects to the associated_document_types list" do
      asociate_document_type = AssociatedDocumentType.create! valid_attributes
      delete :destroy, :id => asociate_document_type.id.to_s
      response.should redirect_to(asociate_document_types_url)
    end
  end

end
