require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmployeeDocumentsController do

  # This should return the minimal set of attributes required to create a valid
  # EmployeeDocument. As you add validations to EmployeeDocument, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all employee_documents as @employee_documents" do
      employee_doc = EmployeeDocument.create! valid_attributes
      get :index
      assigns(:employee_docs).should eq([employee_doc])
    end
  end

  describe "GET show" do
    it "assigns the requested employee_doc as @employee_doc" do
      employee_doc = EmployeeDocument.create! valid_attributes
      get :show, :id => employee_doc.id.to_s
      assigns(:employee_doc).should eq(employee_doc)
    end
  end

  describe "GET new" do
    it "assigns a new employee_doc as @employee_doc" do
      get :new
      assigns(:employee_doc).should be_a_new(EmployeeDocument)
    end
  end

  describe "GET edit" do
    it "assigns the requested employee_doc as @employee_doc" do
      employee_doc = EmployeeDocument.create! valid_attributes
      get :edit, :id => employee_doc.id.to_s
      assigns(:employee_doc).should eq(employee_doc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmployeeDocument" do
        expect {
          post :create, :employee_doc => valid_attributes
        }.to change(EmployeeDocument, :count).by(1)
      end

      it "assigns a newly created employee_doc as @employee_doc" do
        post :create, :employee_doc => valid_attributes
        assigns(:employee_doc).should be_a(EmployeeDocument)
        assigns(:employee_doc).should be_persisted
      end

      it "redirects to the created employee_doc" do
        post :create, :employee_doc => valid_attributes
        response.should redirect_to(EmployeeDocument.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved employee_doc as @employee_doc" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeDocument.any_instance.stub(:save).and_return(false)
        post :create, :employee_doc => {}
        assigns(:employee_doc).should be_a_new(EmployeeDocument)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeDocument.any_instance.stub(:save).and_return(false)
        post :create, :employee_doc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested employee_doc" do
        employee_doc = EmployeeDocument.create! valid_attributes
        # Assuming there are no other employee_documents in the database, this
        # specifies that the EmployeeDocument created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmployeeDocument.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => employee_doc.id, :employee_doc => {'these' => 'params'}
      end

      it "assigns the requested employee_doc as @employee_doc" do
        employee_doc = EmployeeDocument.create! valid_attributes
        put :update, :id => employee_doc.id, :employee_doc => valid_attributes
        assigns(:employee_doc).should eq(employee_doc)
      end

      it "redirects to the employee_doc" do
        employee_doc = EmployeeDocument.create! valid_attributes
        put :update, :id => employee_doc.id, :employee_doc => valid_attributes
        response.should redirect_to(employee_doc)
      end
    end

    describe "with invalid params" do
      it "assigns the employee_doc as @employee_doc" do
        employee_doc = EmployeeDocument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeDocument.any_instance.stub(:save).and_return(false)
        put :update, :id => employee_doc.id.to_s, :employee_doc => {}
        assigns(:employee_doc).should eq(employee_doc)
      end

      it "re-renders the 'edit' template" do
        employee_doc = EmployeeDocument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeDocument.any_instance.stub(:save).and_return(false)
        put :update, :id => employee_doc.id.to_s, :employee_doc => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested employee_doc" do
      employee_doc = EmployeeDocument.create! valid_attributes
      expect {
        delete :destroy, :id => employee_doc.id.to_s
      }.to change(EmployeeDocument, :count).by(-1)
    end

    it "redirects to the employee_documents list" do
      employee_doc = EmployeeDocument.create! valid_attributes
      delete :destroy, :id => employee_doc.id.to_s
      response.should redirect_to(employee_docs_url)
    end
  end

end
