require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KinshipsController do

  # This should return the minimal set of attributes required to create a valid
  # Kinship. As you add validations to Kinship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all kinships as @kinships" do
      kinship = Kinship.create! valid_attributes
      get :index
      assigns(:kinships).should eq([kinship])
    end
  end

  describe "GET show" do
    it "assigns the requested kinship as @kinship" do
      kinship = Kinship.create! valid_attributes
      get :show, :id => kinship.id.to_s
      assigns(:kinship).should eq(kinship)
    end
  end

  describe "GET new" do
    it "assigns a new kinship as @kinship" do
      get :new
      assigns(:kinship).should be_a_new(Kinship)
    end
  end

  describe "GET edit" do
    it "assigns the requested kinship as @kinship" do
      kinship = Kinship.create! valid_attributes
      get :edit, :id => kinship.id.to_s
      assigns(:kinship).should eq(kinship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Kinship" do
        expect {
          post :create, :kinship => valid_attributes
        }.to change(Kinship, :count).by(1)
      end

      it "assigns a newly created kinship as @kinship" do
        post :create, :kinship => valid_attributes
        assigns(:kinship).should be_a(Kinship)
        assigns(:kinship).should be_persisted
      end

      it "redirects to the created kinship" do
        post :create, :kinship => valid_attributes
        response.should redirect_to(Kinship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kinship as @kinship" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kinship.any_instance.stub(:save).and_return(false)
        post :create, :kinship => {}
        assigns(:kinship).should be_a_new(Kinship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kinship.any_instance.stub(:save).and_return(false)
        post :create, :kinship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kinship" do
        kinship = Kinship.create! valid_attributes
        # Assuming there are no other kinships in the database, this
        # specifies that the Kinship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Kinship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => kinship.id, :kinship => {'these' => 'params'}
      end

      it "assigns the requested kinship as @kinship" do
        kinship = Kinship.create! valid_attributes
        put :update, :id => kinship.id, :kinship => valid_attributes
        assigns(:kinship).should eq(kinship)
      end

      it "redirects to the kinship" do
        kinship = Kinship.create! valid_attributes
        put :update, :id => kinship.id, :kinship => valid_attributes
        response.should redirect_to(kinship)
      end
    end

    describe "with invalid params" do
      it "assigns the kinship as @kinship" do
        kinship = Kinship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kinship.any_instance.stub(:save).and_return(false)
        put :update, :id => kinship.id.to_s, :kinship => {}
        assigns(:kinship).should eq(kinship)
      end

      it "re-renders the 'edit' template" do
        kinship = Kinship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kinship.any_instance.stub(:save).and_return(false)
        put :update, :id => kinship.id.to_s, :kinship => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kinship" do
      kinship = Kinship.create! valid_attributes
      expect {
        delete :destroy, :id => kinship.id.to_s
      }.to change(Kinship, :count).by(-1)
    end

    it "redirects to the kinships list" do
      kinship = Kinship.create! valid_attributes
      delete :destroy, :id => kinship.id.to_s
      response.should redirect_to(kinships_url)
    end
  end

end
