require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NumeradorsController do

  # This should return the minimal set of attributes required to create a valid
  # Numerador. As you add validations to Numerador, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all numeradors as @numeradors" do
      numerador = Numerador.create! valid_attributes
      get :index
      assigns(:numeradors).should eq([numerador])
    end
  end

  describe "GET show" do
    it "assigns the requested numerador as @numerador" do
      numerador = Numerador.create! valid_attributes
      get :show, :id => numerador.id.to_s
      assigns(:numerador).should eq(numerador)
    end
  end

  describe "GET new" do
    it "assigns a new numerador as @numerador" do
      get :new
      assigns(:numerador).should be_a_new(Numerador)
    end
  end

  describe "GET edit" do
    it "assigns the requested numerador as @numerador" do
      numerador = Numerador.create! valid_attributes
      get :edit, :id => numerador.id.to_s
      assigns(:numerador).should eq(numerador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Numerador" do
        expect {
          post :create, :numerador => valid_attributes
        }.to change(Numerador, :count).by(1)
      end

      it "assigns a newly created numerador as @numerador" do
        post :create, :numerador => valid_attributes
        assigns(:numerador).should be_a(Numerador)
        assigns(:numerador).should be_persisted
      end

      it "redirects to the created numerador" do
        post :create, :numerador => valid_attributes
        response.should redirect_to(Numerador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved numerador as @numerador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Numerador.any_instance.stub(:save).and_return(false)
        post :create, :numerador => {}
        assigns(:numerador).should be_a_new(Numerador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Numerador.any_instance.stub(:save).and_return(false)
        post :create, :numerador => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested numerador" do
        numerador = Numerador.create! valid_attributes
        # Assuming there are no other numeradors in the database, this
        # specifies that the Numerador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Numerador.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => numerador.id, :numerador => {'these' => 'params'}
      end

      it "assigns the requested numerador as @numerador" do
        numerador = Numerador.create! valid_attributes
        put :update, :id => numerador.id, :numerador => valid_attributes
        assigns(:numerador).should eq(numerador)
      end

      it "redirects to the numerador" do
        numerador = Numerador.create! valid_attributes
        put :update, :id => numerador.id, :numerador => valid_attributes
        response.should redirect_to(numerador)
      end
    end

    describe "with invalid params" do
      it "assigns the numerador as @numerador" do
        numerador = Numerador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Numerador.any_instance.stub(:save).and_return(false)
        put :update, :id => numerador.id.to_s, :numerador => {}
        assigns(:numerador).should eq(numerador)
      end

      it "re-renders the 'edit' template" do
        numerador = Numerador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Numerador.any_instance.stub(:save).and_return(false)
        put :update, :id => numerador.id.to_s, :numerador => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested numerador" do
      numerador = Numerador.create! valid_attributes
      expect {
        delete :destroy, :id => numerador.id.to_s
      }.to change(Numerador, :count).by(-1)
    end

    it "redirects to the numeradors list" do
      numerador = Numerador.create! valid_attributes
      delete :destroy, :id => numerador.id.to_s
      response.should redirect_to(numeradors_url)
    end
  end

end
