require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SicossConditionsController do

  # This should return the minimal set of attributes required to create a valid
  # SicossCondition. As you add validations to SicossCondition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sicoss_conditions as @sicoss_conditions" do
      sicoss_condition = SicossCondition.create! valid_attributes
      get :index
      assigns(:sicoss_conditions).should eq([sicoss_condition])
    end
  end

  describe "GET show" do
    it "assigns the requested sicoss_condition as @sicoss_condition" do
      sicoss_condition = SicossCondition.create! valid_attributes
      get :show, :id => sicoss_condition.id.to_s
      assigns(:sicoss_condition).should eq(sicoss_condition)
    end
  end

  describe "GET new" do
    it "assigns a new sicoss_condition as @sicoss_condition" do
      get :new
      assigns(:sicoss_condition).should be_a_new(SicossCondition)
    end
  end

  describe "GET edit" do
    it "assigns the requested sicoss_condition as @sicoss_condition" do
      sicoss_condition = SicossCondition.create! valid_attributes
      get :edit, :id => sicoss_condition.id.to_s
      assigns(:sicoss_condition).should eq(sicoss_condition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SicossCondition" do
        expect {
          post :create, :sicoss_condition => valid_attributes
        }.to change(SicossCondition, :count).by(1)
      end

      it "assigns a newly created sicoss_condition as @sicoss_condition" do
        post :create, :sicoss_condition => valid_attributes
        assigns(:sicoss_condition).should be_a(SicossCondition)
        assigns(:sicoss_condition).should be_persisted
      end

      it "redirects to the created sicoss_condition" do
        post :create, :sicoss_condition => valid_attributes
        response.should redirect_to(SicossCondition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sicoss_condition as @sicoss_condition" do
        # Trigger the behavior that occurs when invalid params are submitted
        SicossCondition.any_instance.stub(:save).and_return(false)
        post :create, :sicoss_condition => {}
        assigns(:sicoss_condition).should be_a_new(SicossCondition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SicossCondition.any_instance.stub(:save).and_return(false)
        post :create, :sicoss_condition => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sicoss_condition" do
        sicoss_condition = SicossCondition.create! valid_attributes
        # Assuming there are no other sicoss_conditions in the database, this
        # specifies that the SicossCondition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SicossCondition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sicoss_condition.id, :sicoss_condition => {'these' => 'params'}
      end

      it "assigns the requested sicoss_condition as @sicoss_condition" do
        sicoss_condition = SicossCondition.create! valid_attributes
        put :update, :id => sicoss_condition.id, :sicoss_condition => valid_attributes
        assigns(:sicoss_condition).should eq(sicoss_condition)
      end

      it "redirects to the sicoss_condition" do
        sicoss_condition = SicossCondition.create! valid_attributes
        put :update, :id => sicoss_condition.id, :sicoss_condition => valid_attributes
        response.should redirect_to(sicoss_condition)
      end
    end

    describe "with invalid params" do
      it "assigns the sicoss_condition as @sicoss_condition" do
        sicoss_condition = SicossCondition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SicossCondition.any_instance.stub(:save).and_return(false)
        put :update, :id => sicoss_condition.id.to_s, :sicoss_condition => {}
        assigns(:sicoss_condition).should eq(sicoss_condition)
      end

      it "re-renders the 'edit' template" do
        sicoss_condition = SicossCondition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SicossCondition.any_instance.stub(:save).and_return(false)
        put :update, :id => sicoss_condition.id.to_s, :sicoss_condition => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sicoss_condition" do
      sicoss_condition = SicossCondition.create! valid_attributes
      expect {
        delete :destroy, :id => sicoss_condition.id.to_s
      }.to change(SicossCondition, :count).by(-1)
    end

    it "redirects to the sicoss_conditions list" do
      sicoss_condition = SicossCondition.create! valid_attributes
      delete :destroy, :id => sicoss_condition.id.to_s
      response.should redirect_to(sicoss_conditions_url)
    end
  end

end
