require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SicossFormatEmployersController do

  # This should return the minimal set of attributes required to create a valid
  # SicossFormatEmployer. As you add validations to SicossFormatEmployer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sicoss_format_employers as @sicoss_format_employers" do
      sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
      get :index
      assigns(:sicoss_format_employers).should eq([sicoss_format_employer])
    end
  end

  describe "GET show" do
    it "assigns the requested sicoss_format_employer as @sicoss_format_employer" do
      sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
      get :show, :id => sicoss_format_employer.id.to_s
      assigns(:sicoss_format_employer).should eq(sicoss_format_employer)
    end
  end

  describe "GET new" do
    it "assigns a new sicoss_format_employer as @sicoss_format_employer" do
      get :new
      assigns(:sicoss_format_employer).should be_a_new(SicossFormatEmployer)
    end
  end

  describe "GET edit" do
    it "assigns the requested sicoss_format_employer as @sicoss_format_employer" do
      sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
      get :edit, :id => sicoss_format_employer.id.to_s
      assigns(:sicoss_format_employer).should eq(sicoss_format_employer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SicossFormatEmployer" do
        expect {
          post :create, :sicoss_format_employer => valid_attributes
        }.to change(SicossFormatEmployer, :count).by(1)
      end

      it "assigns a newly created sicoss_format_employer as @sicoss_format_employer" do
        post :create, :sicoss_format_employer => valid_attributes
        assigns(:sicoss_format_employer).should be_a(SicossFormatEmployer)
        assigns(:sicoss_format_employer).should be_persisted
      end

      it "redirects to the created sicoss_format_employer" do
        post :create, :sicoss_format_employer => valid_attributes
        response.should redirect_to(SicossFormatEmployer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sicoss_format_employer as @sicoss_format_employer" do
        # Trigger the behavior that occurs when invalid params are submitted
        SicossFormatEmployer.any_instance.stub(:save).and_return(false)
        post :create, :sicoss_format_employer => {}
        assigns(:sicoss_format_employer).should be_a_new(SicossFormatEmployer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SicossFormatEmployer.any_instance.stub(:save).and_return(false)
        post :create, :sicoss_format_employer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sicoss_format_employer" do
        sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
        # Assuming there are no other sicoss_format_employers in the database, this
        # specifies that the SicossFormatEmployer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SicossFormatEmployer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sicoss_format_employer.id, :sicoss_format_employer => {'these' => 'params'}
      end

      it "assigns the requested sicoss_format_employer as @sicoss_format_employer" do
        sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
        put :update, :id => sicoss_format_employer.id, :sicoss_format_employer => valid_attributes
        assigns(:sicoss_format_employer).should eq(sicoss_format_employer)
      end

      it "redirects to the sicoss_format_employer" do
        sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
        put :update, :id => sicoss_format_employer.id, :sicoss_format_employer => valid_attributes
        response.should redirect_to(sicoss_format_employer)
      end
    end

    describe "with invalid params" do
      it "assigns the sicoss_format_employer as @sicoss_format_employer" do
        sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SicossFormatEmployer.any_instance.stub(:save).and_return(false)
        put :update, :id => sicoss_format_employer.id.to_s, :sicoss_format_employer => {}
        assigns(:sicoss_format_employer).should eq(sicoss_format_employer)
      end

      it "re-renders the 'edit' template" do
        sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SicossFormatEmployer.any_instance.stub(:save).and_return(false)
        put :update, :id => sicoss_format_employer.id.to_s, :sicoss_format_employer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sicoss_format_employer" do
      sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
      expect {
        delete :destroy, :id => sicoss_format_employer.id.to_s
      }.to change(SicossFormatEmployer, :count).by(-1)
    end

    it "redirects to the sicoss_format_employers list" do
      sicoss_format_employer = SicossFormatEmployer.create! valid_attributes
      delete :destroy, :id => sicoss_format_employer.id.to_s
      response.should redirect_to(sicoss_format_employers_url)
    end
  end

end
