require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SicossEmployerTypesController do

  # This should return the minimal set of attributes required to create a valid
  # SicossEmployerType. As you add validations to SicossEmployerType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sicoss_employer_types as @sicoss_employer_types" do
      sicoss_employer_type = SicossEmployerType.create! valid_attributes
      get :index
      assigns(:sicoss_employer_types).should eq([sicoss_employer_type])
    end
  end

  describe "GET show" do
    it "assigns the requested sicoss_employer_type as @sicoss_employer_type" do
      sicoss_employer_type = SicossEmployerType.create! valid_attributes
      get :show, :id => sicoss_employer_type.id.to_s
      assigns(:sicoss_employer_type).should eq(sicoss_employer_type)
    end
  end

  describe "GET new" do
    it "assigns a new sicoss_employer_type as @sicoss_employer_type" do
      get :new
      assigns(:sicoss_employer_type).should be_a_new(SicossEmployerType)
    end
  end

  describe "GET edit" do
    it "assigns the requested sicoss_employer_type as @sicoss_employer_type" do
      sicoss_employer_type = SicossEmployerType.create! valid_attributes
      get :edit, :id => sicoss_employer_type.id.to_s
      assigns(:sicoss_employer_type).should eq(sicoss_employer_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SicossEmployerType" do
        expect {
          post :create, :sicoss_employer_type => valid_attributes
        }.to change(SicossEmployerType, :count).by(1)
      end

      it "assigns a newly created sicoss_employer_type as @sicoss_employer_type" do
        post :create, :sicoss_employer_type => valid_attributes
        assigns(:sicoss_employer_type).should be_a(SicossEmployerType)
        assigns(:sicoss_employer_type).should be_persisted
      end

      it "redirects to the created sicoss_employer_type" do
        post :create, :sicoss_employer_type => valid_attributes
        response.should redirect_to(SicossEmployerType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sicoss_employer_type as @sicoss_employer_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        SicossEmployerType.any_instance.stub(:save).and_return(false)
        post :create, :sicoss_employer_type => {}
        assigns(:sicoss_employer_type).should be_a_new(SicossEmployerType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SicossEmployerType.any_instance.stub(:save).and_return(false)
        post :create, :sicoss_employer_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sicoss_employer_type" do
        sicoss_employer_type = SicossEmployerType.create! valid_attributes
        # Assuming there are no other sicoss_employer_types in the database, this
        # specifies that the SicossEmployerType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SicossEmployerType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sicoss_employer_type.id, :sicoss_employer_type => {'these' => 'params'}
      end

      it "assigns the requested sicoss_employer_type as @sicoss_employer_type" do
        sicoss_employer_type = SicossEmployerType.create! valid_attributes
        put :update, :id => sicoss_employer_type.id, :sicoss_employer_type => valid_attributes
        assigns(:sicoss_employer_type).should eq(sicoss_employer_type)
      end

      it "redirects to the sicoss_employer_type" do
        sicoss_employer_type = SicossEmployerType.create! valid_attributes
        put :update, :id => sicoss_employer_type.id, :sicoss_employer_type => valid_attributes
        response.should redirect_to(sicoss_employer_type)
      end
    end

    describe "with invalid params" do
      it "assigns the sicoss_employer_type as @sicoss_employer_type" do
        sicoss_employer_type = SicossEmployerType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SicossEmployerType.any_instance.stub(:save).and_return(false)
        put :update, :id => sicoss_employer_type.id.to_s, :sicoss_employer_type => {}
        assigns(:sicoss_employer_type).should eq(sicoss_employer_type)
      end

      it "re-renders the 'edit' template" do
        sicoss_employer_type = SicossEmployerType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SicossEmployerType.any_instance.stub(:save).and_return(false)
        put :update, :id => sicoss_employer_type.id.to_s, :sicoss_employer_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sicoss_employer_type" do
      sicoss_employer_type = SicossEmployerType.create! valid_attributes
      expect {
        delete :destroy, :id => sicoss_employer_type.id.to_s
      }.to change(SicossEmployerType, :count).by(-1)
    end

    it "redirects to the sicoss_employer_types list" do
      sicoss_employer_type = SicossEmployerType.create! valid_attributes
      delete :destroy, :id => sicoss_employer_type.id.to_s
      response.should redirect_to(sicoss_employer_types_url)
    end
  end

end
