require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiscossRegimenController do

  # This should return the minimal set of attributes required to create a valid
  # SiscossRegiman. As you add validations to SiscossRegiman, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all siscoss_regimen as @siscoss_regimen" do
      siscoss_regiman = SiscossRegiman.create! valid_attributes
      get :index
      assigns(:siscoss_regimen).should eq([siscoss_regiman])
    end
  end

  describe "GET show" do
    it "assigns the requested siscoss_regiman as @siscoss_regiman" do
      siscoss_regiman = SiscossRegiman.create! valid_attributes
      get :show, :id => siscoss_regiman.id.to_s
      assigns(:siscoss_regiman).should eq(siscoss_regiman)
    end
  end

  describe "GET new" do
    it "assigns a new siscoss_regiman as @siscoss_regiman" do
      get :new
      assigns(:siscoss_regiman).should be_a_new(SiscossRegiman)
    end
  end

  describe "GET edit" do
    it "assigns the requested siscoss_regiman as @siscoss_regiman" do
      siscoss_regiman = SiscossRegiman.create! valid_attributes
      get :edit, :id => siscoss_regiman.id.to_s
      assigns(:siscoss_regiman).should eq(siscoss_regiman)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiscossRegiman" do
        expect {
          post :create, :siscoss_regiman => valid_attributes
        }.to change(SiscossRegiman, :count).by(1)
      end

      it "assigns a newly created siscoss_regiman as @siscoss_regiman" do
        post :create, :siscoss_regiman => valid_attributes
        assigns(:siscoss_regiman).should be_a(SiscossRegiman)
        assigns(:siscoss_regiman).should be_persisted
      end

      it "redirects to the created siscoss_regiman" do
        post :create, :siscoss_regiman => valid_attributes
        response.should redirect_to(SiscossRegiman.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved siscoss_regiman as @siscoss_regiman" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossRegiman.any_instance.stub(:save).and_return(false)
        post :create, :siscoss_regiman => {}
        assigns(:siscoss_regiman).should be_a_new(SiscossRegiman)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossRegiman.any_instance.stub(:save).and_return(false)
        post :create, :siscoss_regiman => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested siscoss_regiman" do
        siscoss_regiman = SiscossRegiman.create! valid_attributes
        # Assuming there are no other siscoss_regimen in the database, this
        # specifies that the SiscossRegiman created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiscossRegiman.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => siscoss_regiman.id, :siscoss_regiman => {'these' => 'params'}
      end

      it "assigns the requested siscoss_regiman as @siscoss_regiman" do
        siscoss_regiman = SiscossRegiman.create! valid_attributes
        put :update, :id => siscoss_regiman.id, :siscoss_regiman => valid_attributes
        assigns(:siscoss_regiman).should eq(siscoss_regiman)
      end

      it "redirects to the siscoss_regiman" do
        siscoss_regiman = SiscossRegiman.create! valid_attributes
        put :update, :id => siscoss_regiman.id, :siscoss_regiman => valid_attributes
        response.should redirect_to(siscoss_regiman)
      end
    end

    describe "with invalid params" do
      it "assigns the siscoss_regiman as @siscoss_regiman" do
        siscoss_regiman = SiscossRegiman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossRegiman.any_instance.stub(:save).and_return(false)
        put :update, :id => siscoss_regiman.id.to_s, :siscoss_regiman => {}
        assigns(:siscoss_regiman).should eq(siscoss_regiman)
      end

      it "re-renders the 'edit' template" do
        siscoss_regiman = SiscossRegiman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossRegiman.any_instance.stub(:save).and_return(false)
        put :update, :id => siscoss_regiman.id.to_s, :siscoss_regiman => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested siscoss_regiman" do
      siscoss_regiman = SiscossRegiman.create! valid_attributes
      expect {
        delete :destroy, :id => siscoss_regiman.id.to_s
      }.to change(SiscossRegiman, :count).by(-1)
    end

    it "redirects to the siscoss_regimen list" do
      siscoss_regiman = SiscossRegiman.create! valid_attributes
      delete :destroy, :id => siscoss_regiman.id.to_s
      response.should redirect_to(siscoss_regimen_url)
    end
  end

end
