require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiscossContractModesController do

  # This should return the minimal set of attributes required to create a valid
  # SiscossContractMode. As you add validations to SiscossContractMode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all siscoss_contract_modes as @siscoss_contract_modes" do
      siscoss_contract_mode = SiscossContractMode.create! valid_attributes
      get :index
      assigns(:siscoss_contract_modes).should eq([siscoss_contract_mode])
    end
  end

  describe "GET show" do
    it "assigns the requested siscoss_contract_mode as @siscoss_contract_mode" do
      siscoss_contract_mode = SiscossContractMode.create! valid_attributes
      get :show, :id => siscoss_contract_mode.id.to_s
      assigns(:siscoss_contract_mode).should eq(siscoss_contract_mode)
    end
  end

  describe "GET new" do
    it "assigns a new siscoss_contract_mode as @siscoss_contract_mode" do
      get :new
      assigns(:siscoss_contract_mode).should be_a_new(SiscossContractMode)
    end
  end

  describe "GET edit" do
    it "assigns the requested siscoss_contract_mode as @siscoss_contract_mode" do
      siscoss_contract_mode = SiscossContractMode.create! valid_attributes
      get :edit, :id => siscoss_contract_mode.id.to_s
      assigns(:siscoss_contract_mode).should eq(siscoss_contract_mode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiscossContractMode" do
        expect {
          post :create, :siscoss_contract_mode => valid_attributes
        }.to change(SiscossContractMode, :count).by(1)
      end

      it "assigns a newly created siscoss_contract_mode as @siscoss_contract_mode" do
        post :create, :siscoss_contract_mode => valid_attributes
        assigns(:siscoss_contract_mode).should be_a(SiscossContractMode)
        assigns(:siscoss_contract_mode).should be_persisted
      end

      it "redirects to the created siscoss_contract_mode" do
        post :create, :siscoss_contract_mode => valid_attributes
        response.should redirect_to(SiscossContractMode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved siscoss_contract_mode as @siscoss_contract_mode" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossContractMode.any_instance.stub(:save).and_return(false)
        post :create, :siscoss_contract_mode => {}
        assigns(:siscoss_contract_mode).should be_a_new(SiscossContractMode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossContractMode.any_instance.stub(:save).and_return(false)
        post :create, :siscoss_contract_mode => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested siscoss_contract_mode" do
        siscoss_contract_mode = SiscossContractMode.create! valid_attributes
        # Assuming there are no other siscoss_contract_modes in the database, this
        # specifies that the SiscossContractMode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiscossContractMode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => siscoss_contract_mode.id, :siscoss_contract_mode => {'these' => 'params'}
      end

      it "assigns the requested siscoss_contract_mode as @siscoss_contract_mode" do
        siscoss_contract_mode = SiscossContractMode.create! valid_attributes
        put :update, :id => siscoss_contract_mode.id, :siscoss_contract_mode => valid_attributes
        assigns(:siscoss_contract_mode).should eq(siscoss_contract_mode)
      end

      it "redirects to the siscoss_contract_mode" do
        siscoss_contract_mode = SiscossContractMode.create! valid_attributes
        put :update, :id => siscoss_contract_mode.id, :siscoss_contract_mode => valid_attributes
        response.should redirect_to(siscoss_contract_mode)
      end
    end

    describe "with invalid params" do
      it "assigns the siscoss_contract_mode as @siscoss_contract_mode" do
        siscoss_contract_mode = SiscossContractMode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossContractMode.any_instance.stub(:save).and_return(false)
        put :update, :id => siscoss_contract_mode.id.to_s, :siscoss_contract_mode => {}
        assigns(:siscoss_contract_mode).should eq(siscoss_contract_mode)
      end

      it "re-renders the 'edit' template" do
        siscoss_contract_mode = SiscossContractMode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiscossContractMode.any_instance.stub(:save).and_return(false)
        put :update, :id => siscoss_contract_mode.id.to_s, :siscoss_contract_mode => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested siscoss_contract_mode" do
      siscoss_contract_mode = SiscossContractMode.create! valid_attributes
      expect {
        delete :destroy, :id => siscoss_contract_mode.id.to_s
      }.to change(SiscossContractMode, :count).by(-1)
    end

    it "redirects to the siscoss_contract_modes list" do
      siscoss_contract_mode = SiscossContractMode.create! valid_attributes
      delete :destroy, :id => siscoss_contract_mode.id.to_s
      response.should redirect_to(siscoss_contract_modes_url)
    end
  end

end
